# 机器学习分类模型

## 数据预处理：70%训练数据；30%测试数据

In [56]:
BL = "实践风格" # 逻辑风格、感官风格、计划风格、实践风格
data = pd.read_excel("./test.xlsx") # 测试哪个风格就导入哪个风格数据集
data

,id,第1个行为,第2个行为,第3个行为,第4个行为,第5个行为,第6个行为,第7个行为,第8个行为,第9个行为,...,第24个行为,第25个行为,第26个行为,第27个行为,第28个行为,第29个行为,第30个行为,第31个行为,第32个行为,实践风格
0,1,11,1,3,7,8,5,3,5,6,...,2,6,0,0,0,0,0,0,0,1
1,2,11,1,3,8,7,5,8,6,11,...,4,3,0,0,0,0,0,0,0,1
2,3,8,11,1,3,5,6,11,1,3,...,5,7,0,0,0,0,0,0,0,1
3,4,11,1,2,3,7,5,4,3,11,...,2,7,0,0,0,0,0,0,0,1
4,5,11,1,2,3,11,5,8,3,11,...,5,3,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,896,11,1,3,8,11,5,2,3,7,...,7,8,5,3,5,3,0,0,0,2
896,897,11,1,3,8,7,5,2,4,4,...,8,10,5,3,11,5,3,0,0,2
897,898,11,1,2,4,4,4,3,8,10,...,8,5,2,4,4,4,7,0,0,2
898,899,8,11,1,3,8,7,5,3,8,...,3,7,8,5,3,9,5,6,0,2
899,900,11,1,2,4,4,4,3,8,11,...,4,4,4,3,8,10,5,6,0,2

In [57]:
# 按行打乱所有数据
shuffled_data = data.sample(frac=1, random_state=42)  # random_state 用于设置随机种子 frac=1 表示对所有行进行重排

# 重置索引（可选）
shuffled_data.reset_index(drop=True, inplace=True)
shuffled_data

,id,第1个行为,第2个行为,第3个行为,第4个行为,第5个行为,第6个行为,第7个行为,第8个行为,第9个行为,...,第24个行为,第25个行为,第26个行为,第27个行为,第28个行为,第29个行为,第30个行为,第31个行为,第32个行为,实践风格
0,71,11,1,3,7,5,7,11,8,1,...,7,5,2,7,0,0,0,0,0,1
1,828,11,8,1,2,3,11,5,3,8,...,2,3,7,5,7,0,0,0,0,2
2,232,11,1,2,4,4,4,3,11,1,...,2,3,11,5,3,0,0,0,0,1
3,589,11,1,3,7,8,5,3,7,8,...,3,11,5,3,0,0,0,0,0,2
4,40,11,8,1,2,3,7,5,2,8,...,11,5,6,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,107,11,8,1,3,8,11,5,3,8,...,5,3,5,7,0,0,0,0,0,1
896,271,8,11,1,3,11,5,3,11,1,...,1,3,11,5,7,0,0,0,0,1
897,861,11,8,1,3,8,9,5,2,4,...,5,3,7,8,5,3,0,0,0,2
898,436,11,1,2,4,4,4,3,8,10,...,5,2,8,6,0,0,0,0,0,2
899,103,11,1,2,3,11,5,2,8,6,...,8,5,8,7,0,0,0,0,0,1

In [58]:
X_data = shuffled_data.loc[:,"第1个行为":"第32个行为"].values
X_data.shape

(900, 32)

In [59]:
target = shuffled_data.loc[:,BL].values
target.shape

(900,)

In [60]:
# 切分数据
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X_data,target,test_size=0.3)

display(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(630, 32)

(270, 32)

(630,)

(270,)

## KNN模型训练数据

In [ ]:
from sklearn.neighbors import KNeighborsClassifier # 导入KNN分类库
from sklearn.metrics import classification_report # 生成分类报告

# 1、引入模型
KNN = KNeighborsClassifier()
# 2、训练模型
model = KNN.fit(x_train,y_train)

# 3、计算测试集准确率（accuracy）
print(f'knn测试集准确率：{model.score(x_test,y_test)}')

# 4、打印测试集分类报告
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

## 贝叶斯模型训练数据

In [ ]:
# 导入贝叶斯算法(伯努利模型)
from sklearn.naive_bayes import BernoulliNB

# 1、引入模型
BE = BernoulliNB()
# 2、训练模型
model = BE.fit(x_train,y_train)

# 3、计算测试集准确率（accuracy）
print(f'贝叶斯测试集准确率：{model.score(x_test,y_test)}')

# 4、打印测试集分类报告
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

## 决策树模型训练数据

In [ ]:
from sklearn.tree import DecisionTreeRegressor

# 1、引入模型
DT = DecisionTreeRegressor()
# 2、训练模型
model = DT.fit(x_train,y_train)

# 3、计算测试集准确率（accuracy）
print(f'决策树测试集准确率：{model.score(x_test,y_test)}')

# 4、打印测试集分类报告
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))